# -*- coding: utf-8 -*-
"""datavisualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TySo9WzxhW6gYEX86IvmgaVW6zSfPf_9
"""

import matplotlib

import matplotlib.pyplot as plt

x=[3,8]
x1=[2,7]
y=[7,14]
y1=[8,15]

plt.xlabel("time")
plt.ylabel("distance")
plt.plot(x,y,label='speed of car')
plt.plot(x1,y1,label='speed of truck')
plt.plot(x,y,label='speed of car1')
plt.plot(x1,y1,label='speed of truck1')
plt.grid(color='green')#to drow the grid
plt.legend()
plt.show()
#this is for line representation

plt.xlabel("time")
plt.ylabel("distance")
plt.bar(x,y,label='speed of car')
plt.bar(x1,y1,label='speed of truck')
plt.plot(x,y,label='speed of car1')
plt.plot(x1,y1,label='speed of truck1')
plt.grid(color='green')#to drow the grid
plt.legend()
plt.show()

