# -*- coding: utf-8 -*-
"""graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cggpZ79NulnncAJ3bPkemxwYRV3-OTW_
"""

import numpy as np
np.arange(10)

np.arange(0,100)
len(x)

import matplotlib.pyplot as plt

x=np.arange(0,100,50)
x1=np.arange(0,100,4)
y=[i for i in range(len(x))]
y1=[i for in range(len(x1))]
plt.xlabel("random x")
plt.ylabel("random y")
plt.xlim(0,100)
plt.ylim(0,30)
plt.plot(x,y,label="numpy data view")
plt.plot(x1,y1,label='numpy data view in bar')
plt.plot(x1,y1,lebel='numpy data view in format')
plt.plot(x,y,lebel='numpy data view bar')

plt.legend()
plt.grid(color='g')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
players=["virat","rohit","dhoni","jadeja"]
runs=[1200,800,700,500]
plt.xlabel("cricket players")
plt.ylabel("score")
plt.ylim(400,1300)
plt.bar(players,runs,lebel="performance in 2019",color='r')
plt.legend()
plt.grid(color='g')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
players=["virat","rohit","dhoni","jadeja"]
runs=[1200,800,700,500]
runs1=[1300,900,1100,800]
runs2=[1400,1900,1200,1800]
fig,ax=plt.subplots(3)
#subplot give us two property
#fig   give us entore figure
ax[0].bar(players,runs,color='r')
ax[0].legend()
#ax[0].set_title("performance of 2019")
ax[1].bar(players,runs1,color='green')
ax[1].legend()
#ax[0].set_title("performance of 2020")
fig.suptitle("cricket score analysis")
plt.show()

#pychart
import numpy as np
import matplotlib.pyplot as plt
players=["virat","rohit","dhoni","jadeja"]
runs=[1200,800,700,500]
runs1=[1200,800,700,500]

plt.xlabel("cricket players")
plt.ylabel("score")
plt.pie(runs,labels=players,shadow=True,autopct='%1.1f%%',explode=(0,0,0,0.2))
plt.legend()
plt.show()

fig,ax=plt.subplot(3)
plt.pie(runs,labels=players,shadow=True,autopct='%1.1f%%',explode=(0,0,0,0.2))
ax[0].legend()
plt.pie(run1,labels=players,shadow=True,autopct='%1.1f%%',explode=(0,0.2,0,0))
ax[1].legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x=np.arange(0,100,50)
x1=np.arange(0,100,4)
y=[i for i in range(len(x))]
y1=[i for in range(len(x1))]
plt.xlabel("random x")
plt.ylabel("random y")