# -*- coding: utf-8 -*-
"""pasta1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqisti5hRTdyhBEWHE-5eX4k1Aw-_Y3U
"""

#import the fast AI lirary
import fastai

#import the vision library from fastai
from fastai import vision

#import the all library of vision
#import the error rate matrics for find out the accuray
from fastai.vision import  *
from fastai.metrics import error_rate

#path of the untar data
path=untar_data(URLs.PETS)

#find the path of the the untar data
path

#set the path
!mv '/root/.fastai/data/oxford-iiit-pet'

#find out data
!ls

#untar the file
!untar -xvf pasta.zip

#install the unzip file
!apt install unzip

#print the directory information
!ls

#unzip the pasta file
!unzip pasta.zip

#install the unrar library
!apt install unrar

#unrar the data
!unrar pasta___Google_Search.rar

#path of the pasta 
path=("pasta")

#transform, train and normalized the data
pasta= ImageDataBunch.from_folder(path, train=".", valid_pct=0.2,
        ds_tfms=get_transforms(), size=224, num_workers=4).normalize(imagenet_stats)

#show the data with three batches
pasta.show_batch(3)

#from cnn create model and matrics error rate
model =create_cnn(pasta,models.resnet34,metrics=error_rate)

#fit the model data
model.fit_one_cycle(4)

